name: Linter

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, reopened ]

jobs:
  {% raw -%}
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Version range or exact version to use
    - uses: pre-commit/action@v3.0.0
  {% endraw %}

  golangci-lint:
    strategy:
      matrix:
        go-version: [ {{ cookiecutter.go_version }}.x ]
        os: [ ubuntu-latest ]

    {% raw -%}
    runs-on: ${{ matrix.os }}
    {% endraw %}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          {% raw -%}
          go-version: ${{ matrix.go-version }}
          {% endraw %}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Must be specified without patch version: we always use the latest patch version.
          version: v1.54

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
